import { addDays, subDays } from "date-fns";
import type {
  AuditLog,
  Booking,
  CapacityCategory,
  JobRequest,
  Notification,
  ProviderProfile,
  Quote,
  VerificationRecord,
} from "./types";

const now = new Date("2026-04-18T09:00:00.000Z");

const milestones = [
  {
    label: "Request submitted",
    description: "Buyer requirement captured with audit trail.",
  },
  {
    label: "Provider confirmed",
    description: "Capacity and service documentation acknowledged.",
  },
  {
    label: "Production scheduled",
    description: "Slot reserved with target dispatch plan.",
  },
  {
    label: "In progress",
    description: "Execution underway with milestone oversight.",
  },
  {
    label: "Ready for dispatch",
    description: "Goods staged for handoff or collection.",
  },
  {
    label: "Completed",
    description: "Final job completion signoff and handover documentation recorded.",
  },
] as const;

function makeMilestones(activeIndex: number) {
  return milestones.map((milestone, index) => ({
    id: `milestone-${activeIndex}-${index}`,
    label: milestone.label,
    description: milestone.description,
    state:
      index < activeIndex ? "COMPLETE" : index === activeIndex ? "ACTIVE" : "UPCOMING",
  })) as Booking["milestones"];
}

export const categories: Record<CapacityCategory, string> = {
  FABRICATION: "Light manufacturing",
  PACKAGING: "Packaging & processing",
  WAREHOUSING: "Warehousing",
  COLD_STORAGE: "Cold storage",
  LOGISTICS: "Transport & return-load logistics",
};

export const cities = ["Harare", "Bulawayo", "Gweru", "Mutare", "Masvingo", "Kwekwe"];

export const demoProviders: ProviderProfile[] = [
  {
    id: "provider-1",
    ownerUserId: "user-provider",
    companyName: "Matobo Fabrication Works",
    slug: "matobo-fabrication-works",
    location: "Bulawayo",
    summary:
      "Mid-volume fabrication cell with CNC bending, welding, and light finishing for SME production runs.",
    verificationStatus: "VERIFIED",
    verificationBadgeLabel: "Facility inspected",
    rating: 4.9,
    completedJobs: 128,
    utilizationPercent: 72,
    capacitySharePercent: 28,
    responseHours: 3,
    minimumOrderValue: 3200,
    categories: ["FABRICATION"],
    listings: [
      {
        id: "listing-1",
        providerId: "provider-1",
        title: "Sheet metal fabrication line",
        category: "FABRICATION",
        city: "Bulawayo",
        region: "Matabeleland",
        availableCapacity: "42 machine hours / week",
        leadTimeDays: 7,
        estimatedPriceMin: 3400,
        estimatedPriceMax: 9200,
        unit: "run",
        description: "Laser cutting, bending, and MIG/TIG finishing for short and mid-volume jobs.",
        complianceSummary: "NDA-ready, QA checklist, calibrated tools register.",
        verified: true,
        tags: ["CNC", "Bending", "Short runs"],
      },
    ],
  },
  {
    id: "provider-2",
    ownerUserId: "user-provider-2",
    companyName: "Mukuvisi Packhouse",
    slug: "mukuvisi-packhouse",
    location: "Harare",
    summary:
      "Retail-ready food and FMCG packing partner with batch coding and traceability paperwork.",
    verificationStatus: "VERIFIED",
    verificationBadgeLabel: "Tax status checked",
    rating: 4.8,
    completedJobs: 164,
    utilizationPercent: 81,
    capacitySharePercent: 19,
    responseHours: 2,
    minimumOrderValue: 1800,
    categories: ["PACKAGING"],
    listings: [
      {
        id: "listing-2",
        providerId: "provider-2",
        title: "Batch packing and labeling lane",
        category: "PACKAGING",
        city: "Harare",
        region: "Harare Metro",
        availableCapacity: "18,000 units / week",
        leadTimeDays: 5,
        estimatedPriceMin: 1800,
        estimatedPriceMax: 6400,
        unit: "batch",
        description: "Sleeving, labeling, shrink wrap, outer carton prep, and batch records.",
        complianceSummary: "Batch log, SLA pack, hygiene SOPs.",
        verified: true,
        tags: ["FMCG", "Labeling", "Traceability"],
      },
    ],
  },
  {
    id: "provider-3",
    ownerUserId: "user-provider-3",
    companyName: "Eastern Cold Chain",
    slug: "eastern-cold-chain",
    location: "Mutare",
    summary:
      "Temperature-controlled storage operator with short-term slots for food, pharma, and perishable distribution.",
    verificationStatus: "VERIFIED",
    verificationBadgeLabel: "Cold chain controls reviewed",
    rating: 4.7,
    completedJobs: 93,
    utilizationPercent: 64,
    capacitySharePercent: 36,
    responseHours: 4,
    minimumOrderValue: 2200,
    categories: ["COLD_STORAGE", "WAREHOUSING"],
    listings: [
      {
        id: "listing-3",
        providerId: "provider-3",
        title: "Refrigerated pallet storage",
        category: "COLD_STORAGE",
        city: "Mutare",
        region: "Manicaland",
        availableCapacity: "120 pallet positions",
        leadTimeDays: 2,
        estimatedPriceMin: 2200,
        estimatedPriceMax: 7800,
        unit: "month",
        description: "Short-term cold storage with dock handling and dispatch coordination.",
        complianceSummary: "Temperature logs, handling SOPs, access register.",
        verified: true,
        tags: ["Cold chain", "Pallet storage", "Dock access"],
      },
      {
        id: "listing-4",
        providerId: "provider-3",
        title: "Ambient overflow warehouse",
        category: "WAREHOUSING",
        city: "Mutare",
        region: "Manicaland",
        availableCapacity: "1,300 sqm overflow",
        leadTimeDays: 3,
        estimatedPriceMin: 1600,
        estimatedPriceMax: 5200,
        unit: "month",
        description: "Overflow warehousing for FMCG, packaging materials, and trade inventory.",
        complianceSummary: "Visitor logs, stock reporting, CCTV coverage.",
        verified: true,
        tags: ["Overflow", "Inventory", "Cross-dock"],
      },
    ],
  },
  {
    id: "provider-4",
    ownerUserId: "user-provider-4",
    companyName: "Midlands Fulfilment Hub",
    slug: "midlands-fulfilment-hub",
    location: "Gweru",
    summary:
      "Central warehousing partner suited for national redistribution and short-notice overflow requirements.",
    verificationStatus: "VERIFIED",
    verificationBadgeLabel: "Business registration checked",
    rating: 4.6,
    completedJobs: 117,
    utilizationPercent: 68,
    capacitySharePercent: 32,
    responseHours: 5,
    minimumOrderValue: 1500,
    categories: ["WAREHOUSING", "LOGISTICS"],
    listings: [
      {
        id: "listing-5",
        providerId: "provider-4",
        title: "Overflow warehousing and dispatch prep",
        category: "WAREHOUSING",
        city: "Gweru",
        region: "Midlands",
        availableCapacity: "950 sqm immediately available",
        leadTimeDays: 4,
        estimatedPriceMin: 1500,
        estimatedPriceMax: 4700,
        unit: "month",
        description: "Overflow warehousing with pick-pack and dispatch staging support.",
        complianceSummary: "Stock counts, dispatch logs, contract acknowledgement.",
        verified: true,
        tags: ["Overflow", "Pick-pack", "Dispatch"],
      },
    ],
  },
  {
    id: "provider-5",
    ownerUserId: "user-provider-5",
    companyName: "Masvingo Agro Processing",
    slug: "masvingo-agro-processing",
    location: "Masvingo",
    summary:
      "Agri-processing and contract packaging operator with drying, milling, and retail prep capacity.",
    verificationStatus: "REVIEWING",
    verificationBadgeLabel: "Inspection in review",
    rating: 4.4,
    completedJobs: 76,
    utilizationPercent: 59,
    capacitySharePercent: 41,
    responseHours: 6,
    minimumOrderValue: 1700,
    categories: ["PACKAGING"],
    listings: [
      {
        id: "listing-6",
        providerId: "provider-5",
        title: "Processing and retail pouch line",
        category: "PACKAGING",
        city: "Masvingo",
        region: "Masvingo",
        availableCapacity: "9,500 packs / week",
        leadTimeDays: 8,
        estimatedPriceMin: 1700,
        estimatedPriceMax: 5600,
        unit: "batch",
        description: "Dry blend handling, pouch fill, sealing, coding, and case packing.",
        complianceSummary: "Batch controls, cleaning logs, draft QA plan.",
        verified: false,
        tags: ["Food", "Pouching", "Retail prep"],
      },
    ],
  },
  {
    id: "provider-6",
    ownerUserId: "user-provider-6",
    companyName: "Kwekwe Return Load Network",
    slug: "kwekwe-return-load-network",
    location: "Kwekwe",
    summary:
      "Regional transporter specializing in backhaul and return-load capacity for palletized freight.",
    verificationStatus: "VERIFIED",
    verificationBadgeLabel: "Fleet documents checked",
    rating: 4.7,
    completedJobs: 202,
    utilizationPercent: 84,
    capacitySharePercent: 16,
    responseHours: 2,
    minimumOrderValue: 900,
    categories: ["LOGISTICS"],
    listings: [
      {
        id: "listing-7",
        providerId: "provider-6",
        title: "Return-load pallet transport",
        category: "LOGISTICS",
        city: "Kwekwe",
        region: "Midlands",
        availableCapacity: "7 trucks with weekly backhaul windows",
        leadTimeDays: 2,
        estimatedPriceMin: 900,
        estimatedPriceMax: 3900,
        unit: "trip",
        description: "National linehaul with available return capacity and proof-of-delivery trail.",
        complianceSummary: "Driver register, route logs, POD records.",
        verified: true,
        tags: ["Backhaul", "Linehaul", "Palletized"],
      },
    ],
  },
  {
    id: "provider-7",
    ownerUserId: "user-provider-7",
    companyName: "Belmont Precision Cell",
    slug: "belmont-precision-cell",
    location: "Bulawayo",
    summary:
      "Precision component and enclosure workshop suited to repeat industrial SME orders.",
    verificationStatus: "VERIFIED",
    verificationBadgeLabel: "QA files reviewed",
    rating: 4.8,
    completedJobs: 146,
    utilizationPercent: 77,
    capacitySharePercent: 23,
    responseHours: 4,
    minimumOrderValue: 4100,
    categories: ["FABRICATION"],
    listings: [
      {
        id: "listing-8",
        providerId: "provider-7",
        title: "Precision enclosure production cell",
        category: "FABRICATION",
        city: "Bulawayo",
        region: "Matabeleland",
        availableCapacity: "30 production hours / week",
        leadTimeDays: 6,
        estimatedPriceMin: 4100,
        estimatedPriceMax: 9800,
        unit: "run",
        description: "Small enclosures, brackets, and repeatable metal assemblies.",
        complianceSummary: "Inspection templates, material trace notes, NDA-ready.",
        verified: true,
        tags: ["Precision", "Assemblies", "Repeatable"],
      },
    ],
  },
  {
    id: "provider-8",
    ownerUserId: "user-provider-8",
    companyName: "Harare FlexPack Solutions",
    slug: "harare-flexpack-solutions",
    location: "Harare",
    summary:
      "Contract packaging partner for sachets, sleeves, outer-case work, and promotional rework.",
    verificationStatus: "VERIFIED",
    verificationBadgeLabel: "Service levels filed",
    rating: 4.5,
    completedJobs: 111,
    utilizationPercent: 66,
    capacitySharePercent: 34,
    responseHours: 3,
    minimumOrderValue: 2100,
    categories: ["PACKAGING"],
    listings: [
      {
        id: "listing-9",
        providerId: "provider-8",
        title: "Flexible repack and promo kitting",
        category: "PACKAGING",
        city: "Harare",
        region: "Harare Metro",
        availableCapacity: "24,000 units / week",
        leadTimeDays: 4,
        estimatedPriceMin: 2100,
        estimatedPriceMax: 6800,
        unit: "batch",
        description: "Promo kitting, relabeling, shrink wrap, and retail presentation packs.",
        complianceSummary: "Batch trace sheets, service levels, QA release.",
        verified: true,
        tags: ["Promo", "Repack", "Retail"],
      },
    ],
  },
  {
    id: "provider-9",
    ownerUserId: "user-provider-9",
    companyName: "Mutare Border Storage",
    slug: "mutare-border-storage",
    location: "Mutare",
    summary:
      "Transit and bonded-adjacent storage option for import/export staging and regional redistribution.",
    verificationStatus: "PENDING",
    verificationBadgeLabel: "Verification pending",
    rating: 4.2,
    completedJobs: 41,
    utilizationPercent: 53,
    capacitySharePercent: 47,
    responseHours: 8,
    minimumOrderValue: 1300,
    categories: ["WAREHOUSING"],
    listings: [
      {
        id: "listing-10",
        providerId: "provider-9",
        title: "Transit staging warehouse",
        category: "WAREHOUSING",
        city: "Mutare",
        region: "Manicaland",
        availableCapacity: "620 sqm short-stay storage",
        leadTimeDays: 5,
        estimatedPriceMin: 1300,
        estimatedPriceMax: 4100,
        unit: "month",
        description: "Transit staging for finished goods and imported materials.",
        complianceSummary: "Visitor logs and storage SOPs pending approval.",
        verified: false,
        tags: ["Transit", "Border", "Short-stay"],
      },
    ],
  },
  {
    id: "provider-10",
    ownerUserId: "user-provider-10",
    companyName: "Southern Route Logistics",
    slug: "southern-route-logistics",
    location: "Masvingo",
    summary:
      "Long-haul transporter with return-load lanes connecting Harare, Bulawayo, and the southern corridor.",
    verificationStatus: "VERIFIED",
    verificationBadgeLabel: "Insurance on file",
    rating: 4.6,
    completedJobs: 152,
    utilizationPercent: 74,
    capacitySharePercent: 26,
    responseHours: 4,
    minimumOrderValue: 1200,
    categories: ["LOGISTICS"],
    listings: [
      {
        id: "listing-11",
        providerId: "provider-10",
        title: "Southern corridor return-load capacity",
        category: "LOGISTICS",
        city: "Masvingo",
        region: "Masvingo",
        availableCapacity: "5 weekly linehaul slots",
        leadTimeDays: 3,
        estimatedPriceMin: 1200,
        estimatedPriceMax: 4300,
        unit: "trip",
        description: "Flexible linehaul with proof-of-delivery, dispatch records, and buyer updates.",
        complianceSummary: "POD trail, contract terms, insurer references.",
        verified: true,
        tags: ["Return-load", "Linehaul", "Dispatch"],
      },
    ],
  },
  {
    id: "provider-11",
    ownerUserId: "user-provider-11",
    companyName: "Gweru Metalworks Cooperative",
    slug: "gweru-metalworks-cooperative",
    location: "Gweru",
    summary:
      "Industrial cooperative for fabrication overflow, machine time sharing, and repeat assembly work.",
    verificationStatus: "REVIEWING",
    verificationBadgeLabel: "Governance check in review",
    rating: 4.3,
    completedJobs: 59,
    utilizationPercent: 57,
    capacitySharePercent: 43,
    responseHours: 7,
    minimumOrderValue: 2900,
    categories: ["FABRICATION"],
    listings: [
      {
        id: "listing-12",
        providerId: "provider-11",
        title: "Overflow fabrication and assembly shift",
        category: "FABRICATION",
        city: "Gweru",
        region: "Midlands",
        availableCapacity: "24 fabrication hours / week",
        leadTimeDays: 9,
        estimatedPriceMin: 2900,
        estimatedPriceMax: 7600,
        unit: "run",
        description: "Overflow welding, cutting, assembly, and short industrial production support.",
        complianceSummary: "Basic SOP pack and governance records under review.",
        verified: false,
        tags: ["Overflow", "Assembly", "Cooperative"],
      },
    ],
  },
];

export const demoJobRequests: JobRequest[] = [
  {
    id: "request-1",
    buyerId: "user-buyer",
    title: "Retail display stand fabrication run",
    category: "FABRICATION",
    quantity: 250,
    preferredLocation: "Bulawayo",
    deadline: addDays(now, 12).toISOString(),
    budgetMin: 3500,
    budgetMax: 9000,
    notes: "Powder-coated mild steel stand required for regional rollout.",
    complianceRequirements: "Signed NDA, inspection checklist.",
    status: "MATCHED",
  },
  {
    id: "request-2",
    buyerId: "user-buyer",
    title: "Dry goods repack and coding",
    category: "PACKAGING",
    quantity: 12000,
    preferredLocation: "Harare",
    deadline: addDays(now, 9).toISOString(),
    budgetMin: 2000,
    budgetMax: 6500,
    notes: "Retail-ready pouches with batch coding and case packing.",
    complianceRequirements: "Batch traceability pack.",
    status: "QUOTED",
  },
  {
    id: "request-3",
    buyerId: "user-buyer",
    title: "Overflow cold storage for dairy launch",
    category: "COLD_STORAGE",
    quantity: 90,
    preferredLocation: "Mutare",
    deadline: addDays(now, 5).toISOString(),
    budgetMin: 2400,
    budgetMax: 7800,
    notes: "Short-term pallet storage before eastern corridor distribution.",
    complianceRequirements: "Temperature log access.",
    status: "BOOKED",
  },
  {
    id: "request-4",
    buyerId: "user-buyer",
    title: "Regional return-load distribution",
    category: "LOGISTICS",
    quantity: 18,
    preferredLocation: "Kwekwe",
    deadline: addDays(now, 7).toISOString(),
    budgetMin: 1000,
    budgetMax: 3800,
    notes: "Palletized FMCG loads requiring POD and dispatch updates.",
    complianceRequirements: "POD trail and fleet docs.",
    status: "MATCHED",
  },
  {
    id: "request-5",
    buyerId: "user-buyer",
    title: "Overflow warehousing for import stock",
    category: "WAREHOUSING",
    quantity: 700,
    preferredLocation: "Gweru",
    deadline: addDays(now, 14).toISOString(),
    budgetMin: 1500,
    budgetMax: 4800,
    notes: "Central storage and dispatch staging for six weeks.",
    status: "OPEN",
  },
  {
    id: "request-6",
    buyerId: "user-buyer",
    title: "Agro-processing pouch line backup",
    category: "PACKAGING",
    quantity: 8000,
    preferredLocation: "Masvingo",
    deadline: addDays(now, 16).toISOString(),
    budgetMin: 1800,
    budgetMax: 5400,
    notes: "Secondary processor needed for launch risk mitigation.",
    status: "OPEN",
  },
  {
    id: "request-7",
    buyerId: "user-buyer",
    title: "Enclosure assembly for kiosk rollout",
    category: "FABRICATION",
    quantity: 80,
    preferredLocation: "Bulawayo",
    deadline: addDays(now, 18).toISOString(),
    budgetMin: 4200,
    budgetMax: 9800,
    notes: "Repeat assembly with powder-coat finish.",
    status: "QUOTED",
  },
  {
    id: "request-8",
    buyerId: "user-buyer",
    title: "Cross-border staging warehouse",
    category: "WAREHOUSING",
    quantity: 420,
    preferredLocation: "Mutare",
    deadline: addDays(now, 11).toISOString(),
    budgetMin: 1300,
    budgetMax: 4200,
    notes: "Two-month staging run for imported materials.",
    status: "MATCHED",
  },
];

export const demoQuotes: Quote[] = [
  {
    id: "quote-1",
    jobRequestId: "request-1",
    providerId: "provider-1",
    listingId: "listing-1",
    price: 6200,
    currency: "USD",
    leadTimeDays: 8,
    validUntil: addDays(now, 6).toISOString(),
    notes: "Includes material sourcing, fabrication, and dispatch staging.",
    matchScore: 93,
    matchExplanation: "Strong category fit, same-city execution, and verified fabrication controls.",
    status: "SENT",
  },
  {
    id: "quote-2",
    jobRequestId: "request-1",
    providerId: "provider-7",
    listingId: "listing-8",
    price: 7400,
    currency: "USD",
    leadTimeDays: 7,
    validUntil: addDays(now, 5).toISOString(),
    notes: "Higher precision output with shorter lead window.",
    matchScore: 91,
    matchExplanation: "Excellent quality signal and lead-time fit for repeat fabrication.",
    status: "SENT",
  },
  {
    id: "quote-3",
    jobRequestId: "request-2",
    providerId: "provider-2",
    listingId: "listing-2",
    price: 4100,
    currency: "USD",
    leadTimeDays: 5,
    validUntil: addDays(now, 4).toISOString(),
    notes: "Retail-ready pack, coding, and dispatch prep included.",
    matchScore: 95,
    matchExplanation: "Top packaging fit with traceability paperwork and Harare proximity.",
    status: "ACCEPTED",
  },
  {
    id: "quote-4",
    jobRequestId: "request-2",
    providerId: "provider-8",
    listingId: "listing-9",
    price: 4700,
    currency: "USD",
    leadTimeDays: 4,
    validUntil: addDays(now, 4).toISOString(),
    notes: "Faster turnaround with promo-kitting option.",
    matchScore: 90,
    matchExplanation: "Good packaging match with strong service-level documentation.",
    status: "SENT",
  },
  {
    id: "quote-5",
    jobRequestId: "request-3",
    providerId: "provider-3",
    listingId: "listing-3",
    price: 5200,
    currency: "USD",
    leadTimeDays: 2,
    validUntil: addDays(now, 3).toISOString(),
    notes: "Temperature-controlled handling, dock access, and staging included.",
    matchScore: 96,
    matchExplanation: "Perfect location fit, verified cold-chain controls, and immediate capacity.",
    status: "ACCEPTED",
  },
  {
    id: "quote-6",
    jobRequestId: "request-4",
    providerId: "provider-6",
    listingId: "listing-7",
    price: 1800,
    currency: "USD",
    leadTimeDays: 2,
    validUntil: addDays(now, 5).toISOString(),
    notes: "Backhaul allocation with POD and route updates.",
    matchScore: 94,
    matchExplanation: "Best logistics fit with verified fleet documents and local return-load availability.",
    status: "SENT",
  },
  {
    id: "quote-7",
    jobRequestId: "request-5",
    providerId: "provider-4",
    listingId: "listing-5",
    price: 2900,
    currency: "USD",
    leadTimeDays: 4,
    validUntil: addDays(now, 7).toISOString(),
    notes: "Central warehousing with dispatch staging and stock reporting.",
    matchScore: 92,
    matchExplanation: "Best warehousing fit for central redistribution with verified controls.",
    status: "SENT",
  },
  {
    id: "quote-8",
    jobRequestId: "request-7",
    providerId: "provider-7",
    listingId: "listing-8",
    price: 8200,
    currency: "USD",
    leadTimeDays: 7,
    validUntil: addDays(now, 6).toISOString(),
    notes: "Repeat assembly tooling setup included.",
    matchScore: 94,
    matchExplanation: "High quality and repeatability make this a strong fabrication match.",
    status: "SENT",
  },
  {
    id: "quote-9",
    jobRequestId: "request-8",
    providerId: "provider-3",
    listingId: "listing-4",
    price: 2700,
    currency: "USD",
    leadTimeDays: 3,
    validUntil: addDays(now, 4).toISOString(),
    notes: "Overflow storage with dispatch handling.",
    matchScore: 89,
    matchExplanation: "Strong regional fit with verified warehousing operations.",
    status: "SENT",
  },
  {
    id: "quote-10",
    jobRequestId: "request-8",
    providerId: "provider-9",
    listingId: "listing-10",
    price: 2100,
    currency: "USD",
    leadTimeDays: 5,
    validUntil: addDays(now, 4).toISOString(),
    notes: "Transit staging at lower cost, pending full verification.",
    matchScore: 74,
    matchExplanation: "Budget-friendly and local, but verification status is still pending.",
    status: "SENT",
  },
];

export const demoBookings: Booking[] = [
  {
    id: "booking-1",
    jobRequestId: "request-2",
    quoteId: "quote-3",
    buyerId: "user-buyer",
    providerId: "provider-2",
    status: "IN_PROGRESS",
    contractAcknowledged: true,
    issueFlagged: false,
    milestoneValue: 4100,
    milestones: makeMilestones(3),
  },
  {
    id: "booking-2",
    jobRequestId: "request-3",
    quoteId: "quote-5",
    buyerId: "user-buyer",
    providerId: "provider-3",
    status: "READY_FOR_DISPATCH",
    contractAcknowledged: true,
    issueFlagged: false,
    milestoneValue: 5200,
    milestones: makeMilestones(4),
  },
  {
    id: "booking-3",
    jobRequestId: "request-1",
    quoteId: "quote-1",
    buyerId: "user-buyer",
    providerId: "provider-1",
    status: "PRODUCTION_SCHEDULED",
    contractAcknowledged: true,
    issueFlagged: false,
    milestoneValue: 6200,
    milestones: makeMilestones(2),
  },
];

export const demoVerificationRecords: VerificationRecord[] = [
  {
    id: "verification-1",
    providerId: "provider-1",
    title: "Business registration checked",
    status: "VERIFIED",
    notes: "Company registration and tax registration documents reviewed.",
    checkedAt: subDays(now, 12).toISOString(),
  },
  {
    id: "verification-2",
    providerId: "provider-1",
    title: "Facility inspection completed",
    status: "VERIFIED",
    notes: "Equipment list and workplace safety walkthrough logged.",
    checkedAt: subDays(now, 10).toISOString(),
  },
  {
    id: "verification-3",
    providerId: "provider-5",
    title: "Facility inspection scheduled",
    status: "REVIEWING",
    notes: "Awaiting final inspection notes from field ops.",
    checkedAt: subDays(now, 2).toISOString(),
  },
  {
    id: "verification-4",
    providerId: "provider-9",
    title: "Tax/VAT status review",
    status: "PENDING",
    notes: "Provider uploaded tax status documents for review.",
    checkedAt: subDays(now, 1).toISOString(),
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "notification-1",
    userId: "user-provider",
    title: "New matched request",
    body: "A fabrication buyer request from Bulawayo has been routed to your queue.",
    read: false,
    createdAt: subDays(now, 1).toISOString(),
  },
  {
    id: "notification-2",
    userId: "user-admin",
    title: "Verification review due",
    body: "Three provider files have been awaiting inspection notes for over 48 hours.",
    read: false,
    createdAt: subDays(now, 2).toISOString(),
  },
];

export const demoAuditLogs: AuditLog[] = [
  {
    id: "audit-1",
    actorId: "user-admin",
    action: "verification.approved",
    entityType: "ProviderProfile",
    entityId: "provider-3",
    detail: "Cold-chain controls reviewed and promoted to verified.",
    createdAt: subDays(now, 7).toISOString(),
  },
  {
    id: "audit-2",
    actorId: "user-provider",
    action: "listing.updated",
    entityType: "CapacityListing",
    entityId: "listing-7",
    detail: "Return-load availability adjusted after route plan refresh.",
    createdAt: subDays(now, 3).toISOString(),
  },
];

export const listingLookup = Object.fromEntries(
  demoProviders.flatMap((provider) =>
    provider.listings.map((listing) => [listing.id, { ...listing, provider }]),
  ),
);

export const providerLookup = Object.fromEntries(demoProviders.map((provider) => [provider.id, provider]));
export const jobRequestLookup = Object.fromEntries(demoJobRequests.map((request) => [request.id, request]));
export const quoteLookup = Object.fromEntries(demoQuotes.map((quote) => [quote.id, quote]));
export const bookingLookup = Object.fromEntries(demoBookings.map((booking) => [booking.id, booking]));

export const kpiSnapshot = {
  providers: 11,
  listings: 12,
  buyerRequests: 8,
  quotes: 10,
  activeBookings: 3,
  averageMatchScore: 88,
  verifiedProviders: 8,
  onTimeRate: 94,
};

export const providerUtilizationSeries = [
  { month: "Jan", utilization: 62, demand: 48 },
  { month: "Feb", utilization: 66, demand: 51 },
  { month: "Mar", utilization: 69, demand: 56 },
  { month: "Apr", utilization: 73, demand: 61 },
  { month: "May", utilization: 75, demand: 64 },
  { month: "Jun", utilization: 78, demand: 67 },
];

export const providerCategoryBreakdown = [
  { name: "Fabrication", value: 29 },
  { name: "Packaging", value: 26 },
  { name: "Warehousing", value: 19 },
  { name: "Cold storage", value: 11 },
  { name: "Logistics", value: 15 },
];

export const adminBookingOverview = [
  { stage: "Quoted", count: 10 },
  { stage: "Booked", count: 7 },
  { stage: "In progress", count: 4 },
  { stage: "Ready", count: 2 },
  { stage: "Completed", count: 11 },
];

export const moderationQueue = [
  {
    id: "mod-1",
    provider: "Mutare Border Storage",
    issue: "Verification evidence incomplete",
    risk: "Medium",
  },
  {
    id: "mod-2",
    provider: "Masvingo Agro Processing",
    issue: "Inspection notes pending",
    risk: "Low",
  },
  {
    id: "mod-3",
    provider: "Gweru Metalworks Cooperative",
    issue: "Governance pack under review",
    risk: "Medium",
  },
];

export const complianceRails = [
  "Business registration checked",
  "Tax/VAT status checked",
  "Facility inspection recorded",
  "Service-level documents uploaded",
  "Terms acknowledgement captured",
  "Booking and milestone audit trail maintained",
];
